const colors = {
  WHITE: "#efefef",
  GRAY: "#86888a",
  BLACK: "#272626",
  ORANGE: "#f5793a",
  DARKGRAY: "#404040",
  OPACITY50: "rgba(0, 0, 0, 0.5)",
};

export const COLORS = {
  COMMON: {
    BLUE_LIGHT: "#D4CBE5",
    GREEN_SUPER_LIGHT: "#E5F4E3",
    WHITE: colors.WHITE,
    PALE_WHITE: "#C6C5C7",
    GREEN: "#618C03",
    DARKGREEN: "#538d4e",
    YELLOW: "#F2B705",
    DARKANDYELLOW: "#b59f3b",
    LIGHTGRAY: "#d8d8d8",
    GRAY: colors.GRAY,
    DARKGRAY: "#404040",
    BLACK: colors.BLACK,
    ORANGE: colors.ORANGE,
    BLUE: "#85c0f9",
    RED: "#FF0000",
    COLOR_TONE1: "#d7dadc",
    COLOR_TONE3: "#565758",
    COLOR_TONE5: "#272729",
    COLOR_TONE6: "#1a1a1b",
    COLOR_TONE7: "#121213",
  },
  LIGHT: {
    primary: colors.WHITE,
    background: colors.WHITE,
    card: colors.GRAY,
    text: colors.BLACK,
    border: colors.ORANGE,
    notification: colors.BLACK,
  },
  DARK: {
    primary: colors.BLACK,
    background: colors.BLACK,
    card: colors.WHITE,
    text: colors.WHITE,
    border: colors.ORANGE,
    notification: colors.WHITE,
  },
};
